---
kind: pipeline
type: docker
name: diceroll

steps:
  - name: deploy
    image: docker:latest
    environment:
      BOT_TOKEN:
        from_secret: BOT_TOKEN
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
    commands:
      - docker build -t diceroll .
      - docker stop diceroll || true
      - docker rm diceroll || true
      - docker run -d --restart always -e BOT_TOKEN=$BOT_TOKEN --name diceroll diceroll

volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock
